config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'form', to: 'home#form'
  post 'search', to: 'home#search'
  post 'autocomplete', to: 'home#autocomplete'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    user = User.where(users: auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    user = update_token_info(user, auth) if user.twitter_token.nil? || user.twitter_secret.nil?
    user
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['nickname']
      user.twitter_token = auth['credentials']['token']
      user.twitter_secret = auth['credentials']['secret']
    end
  end

  def self.update_token_info(user, auth)
    user.twitter_token = auth['credentials']['token']
    user.twitter_secret = auth['credentials']['secret']
    user.save!
    user
  end

  def tweet(tweet, user)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_KEY']
      config.consumer_secret     = ENV['TWITTER_SECRET']
      #don't want to tweet yet but comment out when ready
      #config.access_token        = user.twitter_token
      #config.access_token_secret = user.twitter_secret
    end

    client.update(tweet)
  end
end

app/controllers/application_controller.rb
require 'httparty'

class ApplicationController < ActionController::Base

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
require 'services/times_service'
require 'oauth2'
require 'base64'
class HomeController < ApplicationController
  def index
    #yahoo
    #comment in when ready to tweet
    #current_user.tweet('testing the tweets',current_user)
  end

  def form
  end

  def search
    @results = Services::Times.article_search(params)
  end

  def product
  end

  def yahoo
    client_id = ENV['YAHOO_CLIENT_ID']
    client_secret = ENV['YAHOO_CLIENT_SECRET']
    oauth_client = OAuth2::Client.new(client_id, client_secret, {
        site: 'https://api.login.yahoo.com',
        authorize_url: '/oauth2/request_auth',
        token_url: '/oauth2/get_token',
    })

    auth = "Basic #{Base64.strict_encode64("#{client_id}:#{client_secret}")}"

    #with twitter using http://127.0.0.1:3000/ as the callback works. maybe try here?
    #REFRESH TOKEN GET
    new_token = oauth_client.get_token({
                                           redirect_uri: 'https://localnews-staging.herokuapp.com/',
                                           refresh_token: 'ADwx9VdQsu77ZJWJoocCetsA21nF8i8oC7Mw4I9_av4fxYTkC3__TyD2Dc5aVEo-',
                                           grant_type: 'refresh_token',
                                           headers: { 'Authorization' => auth } })
    #OAUTH TOKEN GET
    # binding.pry
    # new_token = oauth_client.get_token({
    #                                        redirect_uri: 'https://localnews-staging.herokuapp.com/',
    #                                        code: 'abcdef',
    #                                        grant_type: 'authorization_code',
    #                                        headers: { 'Authorization' => auth } })

    @result = HTTParty.get("https://fantasysports.yahooapis.com/fantasy/v2/league/359.l.101698/scoreboard;week=5", headers: { Authorization: "Bearer #{ new_token.token }" })
  end

  private

  def autocomplete(params)
    @params = params
    base_url = 'https://maps.googleapis.com/maps/api/place/autocomplete/json'
    input = 'Vict'
    types = 'cities'

    @result = HTTParty.get("#{ base_url }?input=#{ input }&types=(#{ types })&language=en_US&key=#{ ENV['PLACES_API_KEY'] }")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.from_omniauth(auth_hash)
    session[:user_id] = @user.id
    redirect_to '/', notice: 'Signed In!'
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', notice: 'Signed Out!'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    current_user.tweet(twitter_params[:message], current_user)
  end

  def twitter_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.haml
%form{ action: 'search', method: 'post' }
  .small-12.medium-5.columns
    %input{ type: 'search', placeholder: 'city', id: 'input_city', name: 'city' }
  .small-12.medium-5.columns
    %input{ type: 'search', placeholder: 'state', id: 'input_state', name: 'state' }
  .small-12.medium-2.columns
    %input{ type: 'submit', value: 'Submit', :class => 'button' }

app/views/home/autocomplete.haml
%h1 Params
- @params
%h2 Results
- @results

app/views/home/index.haml
#sign-in-twitter
  - if current_user
    = "Signed in as #{ current_user.name }"
    = link_to 'Sign out', signout_path
  - else
    = link_to 'Sign in with Twitter', '/auth/twitter'
  = link_to 'Sign in with Yahoo', '/auth/yahoo'
-#.search-container
-#  .row
-#    .small-12.medium-12.medium-centered.columns
-#      .button
-#        Sign In with Twitter

app/views/home/search.haml
.row
  .small-12.medium-6.medium-centered.columns
    %h1 Your results
.row
  .small-12.medium-6.medium-centered.columns
    .row
      .small-12.columns
        - @results.each do |article|
          %a
            = link_to article[:headline], article[:web_url]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>